---
name: SEI-REF
description: >
  Sistema SEI utilizando a BASE DE REFERÃŠNCIA
version: 0.0.2-sei-rancher
category: EGOV
maintainer: Dirceu Silva <contato@dirceusilva.com>
license: GNU GPL v3
projectURL: https://github.com/contato318/catalogs-rancher-dirceusilva
